import { Dimensions, PixelRatio, StyleSheet } from 'react-native';
import { scale } from 'react-native-size-matters';
import Colors from '../../../constants/Colors';
import {
  FONT_SIZE_LG,
  FONT_SIZE_SM,
  FONT_SIZE_XL,
  POPPINS_MEDIUM,
  POPPINS_REGULAR,
  POPPINS_SEMIBOLD,
  SCREEN_HEIGHT,
  STANDARD_BORDER_RADIUS,
  STANDARD_SPACING,
} from '../../../constants/Constants';

const HAIRLINE = 1 / PixelRatio.get();
const width = Dimensions.get('window').width;

export default StyleSheet.create({
  body: {
    flex: 1,
    backgroundColor: Colors.black,
  },
  photoView: {
    width: '100%',
    height: SCREEN_HEIGHT * 0.5,
    backgroundColor: 'skyblue',
  },
  imageWrapper: {
    height: SCREEN_HEIGHT * 0.5,
  },
  profilePhoto: {
    flex: 1,
    width: null,
    height: null,
    aspectRatio: 1,
  },
  backView: {
    position: 'absolute',
    top: SCREEN_HEIGHT * 0.467,
    right: scale(15),
    width: scale(45),
    height: scale(45),
    borderRadius: scale(22.5),
    backgroundColor: Colors.mainThemeForegroundColor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    width: scale(25),
    height: scale(25),
    resizeMode: 'contain',
    tintColor: 'white',
  },
  titleView: {
    paddingHorizontal: STANDARD_SPACING * 3,
    padding: STANDARD_SPACING * 3,
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: 'red',
  },
  nameText: {
    fontSize: FONT_SIZE_XL,
    fontFamily: POPPINS_SEMIBOLD,
    color: Colors.mainTextColor,
  },
  ageText: {
    paddingLeft: STANDARD_SPACING * 2,
    fontSize: FONT_SIZE_LG,
    fontFamily: POPPINS_MEDIUM,
    color: Colors.mainTextColor,
  },
  captionView: {
    width: '100%',
    paddingHorizontal: STANDARD_SPACING * 2.5,
    paddingBottom: STANDARD_SPACING * 2,
    borderBottomWidth: HAIRLINE,
    borderBottomColor: Colors.hairlineColor,
    // backgroundColor: 'red',
  },
  itemView: {
    width: '100%',
    paddingVertical: 2,
    marginVertical: 2,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  icon: {
    width: scale(20),
    height: scale(20),
    tintColor: 'grey',
  },
  text: {
    paddingLeft: scale(10),
    fontSize: scale(14),
    fontFamily: POPPINS_REGULAR,
    color: Colors.mainTextColor,
    backgroundColor: 'transparent',
  },
  bioView: {
    width: '100%',
    paddingHorizontal: STANDARD_SPACING * 3,
    padding: STANDARD_SPACING * 3,
  },
  label: {
    fontSize: scale(20),
  },
  bioText: {
    fontSize: scale(14),
    fontFamily: POPPINS_REGULAR,
    color: Colors.mainTextColor,
  },
  instagramView: {
    width: '100%',
    height: 270,
    paddingHorizontal: 12,
  },
  slide: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  slideActivity: {
    height: '100%',
    width: '100%',
  },
  myphotosItemView: {
    width: Math.floor(width * 0.27),
    height: Math.floor(width * 0.27),
    marginHorizontal: 8,
    marginVertical: 8,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'grey',
    overflow: 'hidden',
  },
  myphotosView: {
    width: '100%',
    marginTop: scale(10),
    flexDirection: 'row',
  },
  inlineActionsContainer: {
    flex: 1,
    width: '100%',
    backgroundColor: Colors.inlineActionsColor,
    alignSelf: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
  },
  closeButton: {
    alignSelf: 'flex-end',
    height: 24,
    width: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    marginRight: 15,
  },
  closeButton__text: {
    backgroundColor: 'transparent',
    fontSize: 35,
    lineHeight: 35,
    color: '#FFF',
    textAlign: 'center',
  },
  // New styles extracted from inline CSS
  rootContainer: {
    flex: 1,
  },
  reportButton: {
    alignItems: 'center',
    justifyContent: 'center',
    height: scale(40),
    borderRadius: scale(20),
    paddingHorizontal: scale(15),
    borderWidth: scale(0.5),
    borderColor: Colors.orange,
    marginHorizontal: STANDARD_SPACING * 3,
  },
  reportButtonText: {
    fontFamily: POPPINS_MEDIUM,
    fontSize: scale(15),
    color: '#7A7A7A',
    textAlign: 'center',
  },
  distanceText: {
    // marginLeft: 2,
    paddingLeft: scale(10),
    fontSize: scale(14),
    fontFamily: POPPINS_REGULAR,
    color: Colors.mainTextColor,
    backgroundColor: 'transparent',
  },
  photosLabel: {
    fontWeight: 'bold',
  },
  photoFullSize: {
    width: '100%',
    height: '100%',
  },
  swipeControlsContainer: {
    width: '58%',
  },
  swiperDot: {
    backgroundColor: 'rgba(0,0,0,.2)',
    height: 4,
    borderRadius: 4,
    margin: 2,
  },
  swiperActiveDot: {
    backgroundColor: 'white',
    height: 4,
    borderRadius: 4,
    margin: 2,
  },
  instagramSwiperDot: {
    backgroundColor: Colors.grey6,
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  instagramSwiperActiveDot: {
    backgroundColor: Colors.primary,
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
});
