export const defaultProfilePhotoURL =
  'https://firebasestorage.googleapis.com/v0/b/sun-sign-inc-1e12b.appspot.com/o/pics.png?alt=media&token=c387f3dc-00bc-4535-be43-0d46f3b44bc0';

export const Images = {
  Logo: require('../assets/images/Logo1.png'),
  backArrow: require('../assets/icons/png/arrow-back-icon.png'),
  userAvatar: require('../assets/images/default-avatar.jpg'),
  Success: require('../assets/icons/png/toast/success.png'),
  Warning: require('../assets/icons/png/toast/Warning.png'),
  Error: require('../assets/icons/png/toast/error.png'),
  profileTabIcon: require('../assets/images/person-filled-icon.png'),
  swipeTabInactiveIcon: require('../assets/images/logo2.png'),
  swipeTabActiveIcon: require('../assets/images/Logo1.png'),
  chatTabIcon: require('../assets/images/chat-filled-icon.png'),
  accountDetails: require('../assets/images/account-male-icon.png'),
  upgradeAccount: require('../assets/icons/png/vip.png'),
  settings: require('../assets/images/settings-menu-item.png'),
  connectUs: require('../assets/images/contact-call-icon.png'),
  numerology: require('../assets/icons/png/numrology.png'),
  blockedUsers: require('../assets/icons/png/blocked-user-64.png'),
  defaultProfilePhotoURL:
    'https://firebasestorage.googleapis.com/v0/b/sun-sign-inc-1e12b.appspot.com/o/pics.png?alt=media&token=c387f3dc-00bc-4535-be43-0d46f3b44bc0',

  //   BackgroundLayer: require('../assets/images/layerson2.png'),
  //   Dislike: require('../assets/images/dislike.png'),
  //   SuperLike: require('../assets/images/super_like.png'),
  //   Like: require('../assets/images/heart-filled-icon.png'),
  //   home: require('../assets/icons/home-icon.png'),
  //   add_user: require('../assets/icons/add-user-icon.png'),
  //   add_user_filled: require('../assets/icons/add-user-icon-filled.png'),
  //   camera_filled: require('../assets/icons/camera-filled-icon.png'),
  //   camera: require('../assets/icons/camera-icon.png'),
  //   chat: require('../assets/icons/chat-icon.png'),
  //   close: require('../assets/icons/close-x-icon.png'),
  //   checked: require('../assets/icons/checked-icon.png'),
  //   delete: require('../assets/icons/delete.png'),
  //   friends: require('../assets/icons/friends-icon.png'),
  //   inscription: require('../assets/icons/inscription-icon.png'),
  //   menu: require('../assets/icons/menu.png'),
  //   private_chat: require('../assets/icons/private-chat-icon.png'),
  //   search: require('../assets/icons/search-icon.png'),
  //   share: require('../assets/icons/share-icon.png'),
  //   tick: require('../assets/icons/tick.png'),
  //   vip: require('../assets/icons/vip.png'),
  //   undo: require('../assets/icons/undo.png'),
  //   logout: require('../assets/images/logout-menu-item.png'),
  //   instagram: require('../assets/images/icons8-instagram-100.png'),
  //   account: require('../assets/images/account-male-icon.png'),
  //   setting: require('../assets/images/settings-menu-item.png'),
  //   callIcon: require('../assets/images/contact-call-icon.png'),
  //   schoolIcon: require('../assets/images/educate-school-icon.png'),
  //   markerIcon: require('../assets/images/icons8-marker-500.png'),
  //   arrowdownIcon: require('../assets/images/arrow-down-icon.png'),
  //   boederImgSend: require('../assets/images/borderImg1.png'),
  //   boederImgReceive: require('../assets/images/borderImg2.png'),
  //   textBoederImgSend: require('../assets/images/textBorderImg1.png'),
  //   textBoederImgReceive: require('../assets/images/textBorderImg2.png'),
  //   starFilled: require('../assets/images/star-filled-icon2.png'),
  //   crossFilled: require('../assets/images/cross-filled-icon.png'),
};
